name: Deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    name: Deploy
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Set package.json version
        uses: decentraland/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: npm ci

      - run: npm run build

      - name: Publish
        uses: decentraland/oddish-action@master
        with:
          access: public
          provenance: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
