name: Deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    name: Deploy
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set package.json version
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          deterministic-snapshot: true
          only-update-versions: true

      - name: Install
        run: npm ci

      - run: npm run build

      - name: Publish
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          access: public
          provenance: true
