name: Lint Package.json

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-package-json:
    uses: decentraland/platform-actions/.github/workflows/lint-package-json.yml@6a3a143a295aca589af92c6ad8f85f9fa27ec15f # main
